// src/types/product-adapter.ts

import { IProductItem as MinimalProduct } from './product-minimal';
import { IProductItemProps as ZoneProduct } from './product';

export const adaptMinimalToZoneProduct = (minimalProduct: MinimalProduct): ZoneProduct => ({
  id: minimalProduct.id,
  name: minimalProduct.name,
  label: minimalProduct.newLabel.enabled ? 'new' : minimalProduct.saleLabel.enabled ? 'sale' : '',
  caption: minimalProduct.subDescription || '',
  description: minimalProduct.description,
  coverImg: minimalProduct.coverUrl,
  category: minimalProduct.category,
  sold: minimalProduct.totalSold,
  price: minimalProduct.price,
  rating: minimalProduct.totalRatings || 0,
  priceSale: minimalProduct.priceSale || 0,
  inStock: minimalProduct.available,
  review: minimalProduct.totalReviews,
  images: minimalProduct.images,
  sku: minimalProduct.sku,
  code: minimalProduct.code,
  taxes: minimalProduct.taxes,
  tags: minimalProduct.tags,
  sizes: minimalProduct.sizes,
  gender: minimalProduct.gender,
  colors: minimalProduct.colors,
  publish: minimalProduct.publish,
  quantity: minimalProduct.quantity,
  available: minimalProduct.available,
  totalSold: minimalProduct.totalSold,
  totalRatings: minimalProduct.totalRatings,
  totalReviews: minimalProduct.totalReviews,
  createdAt: minimalProduct.createdAt,
  inventoryType: minimalProduct.inventoryType,
  subDescription: minimalProduct.subDescription,
  isPublished: minimalProduct.isPublished,
  reviews: minimalProduct.reviews,
  ratings: minimalProduct.ratings,
  saleLabel: minimalProduct.saleLabel,
  newLabel: minimalProduct.newLabel,
  vendor: minimalProduct.vendor,
});